// GENERATED by deploy/sw.mjs — do not edit by hand (`deno run -A deploy/sw.mjs`; --check gates it).
// Scope comes from this file's own path, so every app needs its own worker; the logic lives once in
// /_rt/sw-core.js. `precache` is this app's shell — enough to boot with the network unplugged.
self.MS = {
  app: "muzak",
  version: "c44bf894fc",
  precache: [
    "./",
    "./icon.svg",
    "./icon.webp",
    "./index.html",
    "./manifest.json",
    "./view.js",
    "/_rt/decor.css",
    "/_rt/runtime.css",
    "/_rt/theme-lum.css",
    "/_rt/theme.css",
    "/_rt/themes.json",
    "https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4",
    "https://cdn.jsdelivr.net/npm/daisyui@5",
    "https://cdn.jsdelivr.net/npm/daisyui@5/themes.css",
    "https://code.iconify.design/iconify-icon/3.0.0/iconify-icon.min.js",
    "https://fonts.googleapis.com/css2?family=Geist:wght@400..700&family=Geist+Mono:wght@400..600&display=swap",
  ],
};
importScripts("/_rt/sw-core.js");
